version: "3.8"

services:
  frontend:
    build:
      context: ./business_web
      dockerfile: Dockerfile
    container_name: business_web
    ports:
      - "3000:3000"
    volumes:
      - ./business_web:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - REACT_APP_BACKEND_URL=http://backend:8080/api
    depends_on:
      - backend
